title: TFI STL's
description: A location housing images of my STL collection
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

search_enabled: true
